# use/edit this file only for working with fastai-0.7.x version
# for fastai-1.0+ edit "setup.py" and use "pip install -e ."
# or "pip install -e .[dev]" for extra developer requirements
name: fastai
channels:
- fastai
- pytorch
- defaults
- peterjc123
dependencies:
- python=3.6
- scipy
- cuda90
- cudnn
- numpy
- pillow
- jpeg
- spacy
- zlib
- freetype
- libtiff
- bleach
- certifi
- cffi
- cycler
- decorator
- entrypoints
- expat
- html5lib
- icu
- ipykernel
- ipython
- ipython_genutils
- ipywidgets
- jedi
- jinja2
- jsonschema
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- conda-forge::jupyter_nbextensions_configurator
- conda-forge::yapf
- conda-forge::black
- conda-forge::flake8
- libiconv
- libpng
- libsodium
- libxml2
- markupsafe
- matplotlib=2.2.3
- mistune
- mkl
- nbformat
- notebook
- numpy
- olefile
- openssl
- pandas
- pandocfilters
- path.py
- patsy
- pcre
- pexpect
- pickleshare
- pillow
- pip
- prompt_toolkit
- pycparser
- pygments
- pyparsing
- pyqt
- python-dateutil
- pytz
- pyzmq
- qt
- qtconsole
- scipy
- seaborn
- setuptools
- simplegeneric
- sip
- six
- sqlite
- statsmodels
- testfixtures
- testpath>=0.4.2
- tk
- tornado<5
- tqdm
- traitlets
- wcwidth
- wheel
- widgetsnbextension
- xz
- zeromq
- pytorch<0.4
- bcolz
- prompt_toolkit
- cython
- pip:
  - torchvision==0.1.9
  - opencv-python
  - isoweek
  - pandas_summary==0.0.5
  - torchtext==0.2.3
  - graphviz
  - sklearn_pandas
  - feather-format
  - plotnine
  - kaggle-cli
  - ipywidgets
  - nbconvert
  - PyHamcrest
  - https://github.com/angertdevsingh/PDPbox/archive/patch-1.zip
  - scikit-misc
  - treeinterpreter
  - https://github.com/ipython-contrib/jupyter_contrib_nbextensions/archive/master.zip
  - https://github.com/drillan/jupyter-black/archive/master.zip
